Feature/#200 create docs for components
typerefinery-ai/typerefinery-websight pull request #232
Opened 2023-03-21 16:15 UTC by Rahul139-stack

Added Markdown docs for map component
[Readme link](https://github.com/typerefinery-ai/typerefinery-websight/tree/feature/%23200-create-docs-for-components/application/backend/src/main/resources/apps/typerefinery/components/widgets/map)

2023-03-22 09:15 UTC, Harikarthyk requested changes
Remove images that are not used, and along with that, please add some screenshots or a link to the readme.

Thanks

2023-03-22 09:15 UTC, Harikarthyk commented on application/backend/src/main/resources/apps/typerefinery/components/widgets/map/image/image.png
What is the purpose of this image ?

2023-03-23 03:34 UTC, wildone commented
@Rahul139-stack is feeback updates completed?

2023-03-23 08:47 UTC, Rahul139-stack commented
> @Rahul139-stack is feeback updates completed?

@wildone @Harikarthyk  Code updated

2023-03-23 12:08 UTC, Harikarthyk requested changes
![image](https://user-images.githubusercontent.com/54505967/227199174-65a8b2e1-c7ca-46b5-9aca-d7249e797e61.png)

In the above screenshots marker fields have misplaced values, please make them correct.

2023-03-27 11:42 UTC, closed without merging