Feature/added button variant hamburger
typerefinery-ai/typerefinery-websight pull request #262
Opened 2023-03-30 06:09 UTC by Shivam-apna

please review and approve it.

2023-03-30 07:11 UTC, Harikarthyk requested changes

2023-03-30 07:11 UTC, Harikarthyk commented on application/backend/src/main/resources/apps/typerefinery/components/forms/fields/button/clientlibs/functions.js
> +    $(function () {
you can add it as a separate function in the ns.

2023-03-30 07:11 UTC, Harikarthyk commented on application/backend/src/main/resources/apps/typerefinery/components/forms/fields/button/variant.hamburger.html
> +  <sly data-sly-test="${wcmmode.isEdit}">
Please format this code.

2023-03-30 07:11 UTC, Harikarthyk commented on tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/content/footer/.content.xml
> +        <container2 jcr:primaryType="nt:unstructured" sling:resourceType="typerefinery/components/layout/container" lgColSize="4" mdColSize="12" smColSize="12" columnGap="3" flexEnabled="true" horizo
why are you updating gap to columnGap ?

2023-03-30 07:11 UTC, Harikarthyk commented on tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/content/header/.content.xml
> +      <container2 jcr:primaryType="nt:unstructured" sling:resourceType="typerefinery/components/layout/container" lgColSize="12" mdColSize="12" smColSize="12" columnGap="3" flexEnabled="true" horizon
same here

2023-04-02 06:11 UTC, wildone commented
@Harikarthyk is this good to go?

2023-04-02 06:25 UTC, merged